import type { GetStaticProps, GetStaticPropsContext } from 'next'
import Head from 'next/head'
import getLayoutData from '../data/layout'
import Layout from '../components/layout'
import { getPageData } from '../data/page'
import {
  HeroUnit,
  HeroContent,
  HeroContentProps
} from '../components/hero-unit'
import Container from 'react-bootstrap/Container'
import Row from 'react-bootstrap/Row'
import Col from 'react-bootstrap/Col'
import styles from '../styles/index.module.scss'
import Image from 'next/image'
import FlexibleContent, { Layouts } from '../components/flexible-content'
import links from '../styles/links.module.scss'
import Link from 'next/link'
import { PageProps } from './[slug]'
import { WordPressImage, WordPressPage } from '../data/types'
import { getImageData } from '../data'

interface HomePage extends WordPressPage {
  acf: HeroContentProps & {
    featured_image: WordPressImage
    featured_content: string
    layouts: Layouts[]
  }
}

interface HomePageProps extends PageProps {
  page: HomePage
}

export default function Home(props: HomePageProps) {
  const hasFeaturedImage = !!props.page.acf.featured_image
  return (
    <Layout {...props}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <HeroUnit imgSrc={props.heroImg.media_details.sizes.full.source_url}>
        <HeroContent
          content={props.page.acf.content}
          buttons={props.page.acf.buttons}
        />
      </HeroUnit>
      <Container className={styles.featuredContainer}>
        <Row>
          <Col>
            <h2
              className={
                hasFeaturedImage
                  ? `${styles.featureTitle} ${styles.featuredImage}`
                  : styles.featureTitle
              }
            >
              Featured
            </h2>
          </Col>
        </Row>
        <Row>
          {hasFeaturedImage && (
            <Col className={styles.column} xs={12} lg={6}>
              <Image
                src={props.page.acf.featured_image.sizes.medium_large}
                alt={props.page.acf.featured_image.alt}
                width={
                  props.page.acf.featured_image.sizes['medium_large-width']
                }
                height={
                  props.page.acf.featured_image.sizes['medium_large-height']
                }
              />
            </Col>
          )}
          <Col className={styles.column} xs={12} lg={hasFeaturedImage ? 6 : 12}>
            <div
              className={styles.wpContent}
              dangerouslySetInnerHTML={{
                __html: props.page.acf.featured_content
              }}
            />
            <Link href='/gallery/'>
              <a className={`${links.buttonLink} ${links.secondary}`}>
                View Gallery
              </a>
            </Link>
          </Col>
        </Row>
      </Container>
      {props.page.acf.layouts && (
        <FlexibleContent layouts={props.page.acf.layouts} />
      )}
    </Layout>
  )
}

export const getStaticProps: GetStaticProps = async (
  context: GetStaticPropsContext
) => {
  const layoutData = await getLayoutData()
  const pageData = await getPageData('home')
  return {
    props: {
      ...layoutData,
      ...pageData
    }
  }
}
